global using DMS.Data.Entities.Commen;
global using DMS.Data.Entities;
global using DMS.Data.Models.Documents;
global using OneOf;
global using Microsoft.EntityFrameworkCore;
global using DMS.Data.Models.Tags;
// global using DMS.Helper;
global using FluentValidation;
global using DMS.Data.Models.Categories;
global using DMS.Data.Repo;
global using EC499.DMS.Data.Models.Categories;
global using Microsoft.AspNetCore.Mvc;
